version: 2.1

jobs:

  checkout_code:
    docker:
      - image: debian:buster
    steps:
      - run:
          name: Install Dependencies
          command: 'apt-get update && apt-get install -y ca-certificates'
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ./
  build:
    docker:
      - image: debian:buster
    parameters:
      community:
        type: string
      profile:
        type: string
      device:
        type: string
    steps:
      - run:
          name: Install Dependencies
          command: 'apt-get update && apt-get install -y gnupg aria2 xz-utils make perl gcc g++ libncurses5-dev gawk unzip bzip2 wget python3 git file ca-certificates'
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Patch Bin Directory
          command: sed -i '/BIN_DIR=/ s/$PROFILE_PATH\/bin\/$3/\/tmp\/artifacts\/$1\/$2\/$3/' ./build
      - run:
          name: Build << parameters.community >> << parameters.profile >> << parameters.device >>
          command: './build << parameters.community >> << parameters.profile >> << parameters.device >>'
      - persist_to_workspace:
          root: /tmp/artifacts
          paths: ./*

  deploy:
    docker:
      - image: debian:buster
    working_directory: /tmp/artifacts
    steps:
      - run:
          name: Install Dependencies
          command: 'apt-get update && apt-get install -y git ca-certificates'
      - add_ssh_keys:
          fingerprints:
            - "9c:ec:6c:01:d7:c6:10:2d:a5:41:ab:c3:ef:44:13:46"
      - attach_workspace:
          at: /tmp/artifacts
      - store_artifacts:
          path: '/tmp/artifacts'
          destination: '/'
      - deploy:
          name: "Publish Artifacts"
          command: |
            git init
            git config user.email "circle@circleci.com"
            git config user.name "CircleCI"
            git remote add origin git@github.com:MassMesh/meta-imagebuilder-artifacts.git
            git add .
            git commit -m "Commit artifacts."
            GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git push -u origin "${CIRCLE_BRANCH}" --force

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code
      - build:
          name: build_1
          community: massmesh
          profile: meshnode
          device: rpi-4
          requires:
            - checkout_code
      - build:
          name: build_2
          community: massmesh
          profile: meshnode
          device: apu2
          requires:
            - checkout_code
      - build:
          name: build_3
          community: massmesh
          profile: meshnode
          device: globalscale_espressobin
          requires:
            - checkout_code
      - build:
          name: build_4
          community: massmesh
          profile: meshradio
          device: ubnt_nanostation-ac-loco
          requires:
            - checkout_code
      - build:
          name: build_5
          community: massmesh
          profile: meshradio
          device: ubnt_unifiac-mesh
          requires:
            - checkout_code
      - deploy:
          requires:
            - build_1
            - build_2
            - build_3
            - build_4
            - build_5
